### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by plboerboom** [yosqueoy/echo_ex#1]
Would you consider adding a license to this project -- maybe MIT?

I'm looking for something small and lightweight to add standardized logging to some existing bash scripts and this looks useful, but I don't want to just grab it without your consent.

The project I'd use it in is commercial, but the code wouldn't be redistributed.

**Comment by yosqueoy** [comment]
Added MIT license. Thanks for your suggestion.

**Comment by plboerboom** [comment]
Thanks!
